version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tax-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tax_db
    ports:
      - "5433:5432"
